# Generated by Django 3.1.8 on 2022-06-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(),
        ),
    ]
