# Generated by Django 3.1.8 on 2022-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20220623_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Roll_no',
            field=models.PositiveIntegerField(),
        ),
    ]
