# Generated by Django 3.1.8 on 2022-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20220623_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('department', models.CharField(choices=[('1', 'HR'), ('2', 'Software'), ('3', 'Marketing')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
