# Generated by Django 3.1.8 on 2022-06-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20220624_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.student'),
        ),
    ]
