# Generated by Django 3.1.8 on 2022-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20220624_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='many',
            field=models.ManyToManyField(to='newapp.student', verbose_name='many'),
        ),
    ]
