# Generated by Django 3.1.8 on 2022-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_auto_20220624_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='many',
            field=models.ManyToManyField(to='newapp.student', verbose_name='Employee'),
        ),
    ]
