# Generated by Django 3.1.8 on 2022-06-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_auto_20220624_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='many',
        ),
        migrations.AddField(
            model_name='employee',
            name='info',
            field=models.ManyToManyField(related_name='Employee', to='newapp.student'),
        ),
    ]
