# Generated by Django 3.1.8 on 2022-06-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_auto_20220624_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=40, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_no',
            field=models.PositiveIntegerField(null=b'I01\n'),
        ),
    ]
